/*
 * actionneurs_define.h
 *
 *  Created on: 9 mai 2022
 *      Author: thibault
 */

#ifndef INC_ACTIONNEURS_DEFINE_H_
#define INC_ACTIONNEURS_DEFINE_H_

#define RESISTANCE_REF 1000
#define RESISTANCE_MAX 3.3
#define TEMPS_ACTION_RESISTANCE 2000
#define TIMEOUT_HADC 300

#define VIN_DIVISEUR 4096
#define VIN_TENSION 3.3

#define RESISTANCE_JAUNE_MIN 300 //Valeur exacte 470
#define RESISTANCE_JAUNE_MAX 640
#define RESISTANCE_VIOLET_MIN 640 //Valeur exacte 1000
#define RESISTANCE_VIOLET_MAX 1360
#define RESISTANCE_INTERDIT_MIN 3000 //valeur exacte 4700
#define RESISTANCE_INTERDIT_MAX 6400

#define ANGLE_RESISTANCE_REFERENCE 35
#define PAS_SERVO_RESISTANCE 0.46

#define ON 1
#define OFF 0

#endif /* INC_ACTIONNEURS_DEFINE_H_ */
