M48
; DRILL file {KiCad (6.0.0)} date Fri May 13 11:59:05 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-13T11:59:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.0984Y-3.4449
X5.0984Y-6.3583
X5.9646Y-3.4449
X5.9646Y-6.3583
T0
M30
