M48
; DRILL file {KiCad (6.0.0)} date Mon May  9 16:09:25 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-09T16:09:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X92.952Y-40.448
X92.952Y-120.448
X147.952Y-40.448
X147.952Y-120.448
T0
M30
