/*
 * TOF_Errors.h
 *
 *  Created on: May 8, 2022
 *      Author: Samuel
 */

#ifndef VL53L0X_PLATFORM_TOF_ERRORS_H_
#define VL53L0X_PLATFORM_TOF_ERRORS_H_

#include "../Inc/vl53l0x_api.h"

typedef enum {
	TOF_STATUS_SUCESS = VL53L0X_ERROR_NONE,
	TOF_STATUS_ERROR_CALIBRATION_WARNING = VL53L0X_ERROR_CALIBRATION_WARNING,
	TOF_STATUS_ERROR_MIN_CLIPPED = VL53L0X_ERROR_MIN_CLIPPED,
	TOF_STATUS_ERROR_UNDEFINED = VL53L0X_ERROR_UNDEFINED,
	TOF_STATUS_ERROR_INVALID_PARAMS = VL53L0X_ERROR_INVALID_PARAMS,
	TOF_STATUS_ERROR_NOT_SUPPORTED = VL53L0X_ERROR_NOT_SUPPORTED,
	TOF_STATUS_ERROR_RANGE_ERROR = VL53L0X_ERROR_RANGE_ERROR,
	TOF_STATUS_ERROR_TIME_OUT = VL53L0X_ERROR_TIME_OUT,
	TOF_STATUS_ERROR_MODE_NOT_SUPPORTED = VL53L0X_ERROR_MODE_NOT_SUPPORTED,
	TOF_STATUS_ERROR_BUFFER_TOO_SMALL = VL53L0X_ERROR_BUFFER_TOO_SMALL,
	TOF_STATUS_ERROR_GPIO_NOT_EXISTING = VL53L0X_ERROR_GPIO_NOT_EXISTING,
	TOF_STATUS_ERROR_GPIO_FUNCTIONALITY_NOT_SUPPORTED = VL53L0X_ERROR_GPIO_FUNCTIONALITY_NOT_SUPPORTED,
	TOF_STATUS_ERROR_INTERRUPT_NOT_CLEARED = VL53L0X_ERROR_INTERRUPT_NOT_CLEARED,
	TOF_STATUS_ERROR_CONTROL_INTERFACE = VL53L0X_ERROR_CONTROL_INTERFACE,
	TOF_STATUS_ERROR_INVALID_COMMAND = VL53L0X_ERROR_INVALID_COMMAND,
	TOF_STATUS_ERROR_DIVISION_BY_ZERO = VL53L0X_ERROR_DIVISION_BY_ZERO,
	TOF_STATUS_ERROR_REF_SPAD_INIT = VL53L0X_ERROR_REF_SPAD_INIT,
	TOF_STATUS_ERROR_NOT_IMPLEMENTED = VL53L0X_ERROR_NOT_IMPLEMENTED,
	TOF_STATUS_CONFIG_UNKNOWN_RANGING_MODE,
	TOF_STATUS_SENSORS_MISSING
} TOF_Status_t;

#endif /* VL53L0X_PLATFORM_TOF_ERRORS_H_ */
